export enum ESocketIncomeEvent {
    JOIN_ROOM = 'JOIN_ROOM',
    START_GAME = 'START_GAME',
    PICK_CARD = 'PICK_CARD',
    VOTE = 'VOTE',
    LEAVE_GAME = 'LEAVE_GAME',
}

export enum ESocketOutcomeEvent {
    PLAYER_JOINED = 'PLAYER_JOINED',
    PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
    PLAYER_RECONNECTED = 'PLAYER_RECONNECTED',
    GAME_STARTED = 'GAME_STARTED',
    GAME_PAUSED = 'GAME_PAUSED',
    GAME_RESUMED = 'GAME_RESUMED',
    ROUND_STAGE_CHANGED = 'ROUND_STAGE_CHANGED',
    ERROR = 'ERROR',
}
